# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d185f1aea87e7b9d9cf24c8b82bccf79979ab10c26496f4d9d0c1167effeca7eb8ce3a291987ee995afb6954896a285624dc2d9187bf527057bc43bc9b0c458d

test:
  secret_key_base: 4f9fe8a2f1cdcce3f36aad2041d536d4d8b805c8d8bb50d768163b45697e217f8a80ec8e3479e48138ef29ee818c3906d8638a895962349e3660f7b404bf32d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
